%% Vortex-antivortex magnetization state peak analyzer
%
%  peakFinder reads from the A_ii.ovf files generated by mumax3 a matrix
%  corresponding to the mz values; performs a five-point 2D Gaussian least
%  squares fit to locate the peak, and plots its position in time.
%
%  To help the program locate a peak when there's "turbulence" in mz, the
%  xSlicel, xSlicer, ySliceu, ySliced parameters can be used to exclude
%  regions containing unwanted peaks.
%
%  For accessory functions, see also: GAUSSIANPEAK RENAMEFILES
%

clear variables
close all

%% Simulation parameters

% Nx = 128;
% Ny = 128;
c = 2.5e-9;                          % cell size

nz = 1;

% N = 201;                           % number of data files
% columns = 1;                       % number of columns of data in the files
% files renaming
rename = true;

% saving of 3D stills
stills = 'y';

%% Files folder and files rename

dailyFolder = 'D:\Program Files\mumax\Simulazioni\NUOVE\gradient+gaussianspot\';
simulationFolder = 'nanodot_thermal_uniform_ENERGY\';

folder = [dailyFolder simulationFolder];            % folder containing files
PythonScript = 'batchRenamer.py';                   % Python rename script

% calls the MATLAB wrapper to a pyhton function (requires python 3.5 or
% above)

if rename
    try
        renameFiles(folder,PythonScript);
    catch
        disp('Error: files already renamed. Continuing execution...')
    end
end

%% Extract data from table

fid = fopen([folder 'table.txt']);
fgets(fid);                                     % skip first line
matrix = cell2mat(textscan(fid, '%f %f %f %f %f %*[^\n]'));   % read time column, ignore rest
Ku = matrix(:,5);
Nfiles = length(Ku);
% Nfiles = 20;
fclose(fid);

%%
%read the size of matrix
% files reading
fid = fopen([folder 'A_1.ovf']);

% read the M columns
Evec = cell2mat(textscan(fid,'%f%*[^\n]','CommentStyle','#'));
fclose(fid);

Evec = Evec(1:(length(Evec)/nz));

N = sqrt(length(Evec));
clear Evec

x = linspace(-c/2*(N-1),c/2*(N-1),N);
y = linspace(-c/2*(N-1),c/2*(N-1),N);
[X,Y] = meshgrid(x,y);

if stills == 'y'
    [Xq,Yq] = meshgrid(linspace(min(x),max(x),length(x)*5)*1e9);
end

r = linspace(0,c*(N-1)/2,N/2); % The vector of values of r to integrate

% Pre-allocate for speed
cumEnergy = zeros(size(r)); % This will store the volumes for each r
Edtot = zeros(N,N);
% main loop
for ii = 1:Nfiles
    % files reading
    fid = fopen([folder 'A_' num2str(ii) '.ovf']);
    
    % read the M columns
    Evec = cell2mat(textscan(fid,'%f%*[^\n]','CommentStyle','#'));
    fclose(fid);
    
    Evec = Evec(1:(length(Evec)/nz));
    
    % put Mz into matrix form
    Ed = reshape(Evec,[N,N]);
    Ed = rot90(Ed,1);
    Edtot = Edtot + Ed;
%      Ed(Ed == 0) = NaN;
    %%
%     EdTensor(:,:,ii) = Ed;
    %%
    clear Evec
    %%
    
    % For each element in rVolume, create a filter function that is zero outside
    % of the radius of interest. Then multiply the original data by the filter before
    % integration. This way, the data can be easily integrated over the cylindrical
    % region of interest.
%     for jj=1:length(r)
%         % Create a filter for the original data
%         filter = sqrt(X.^2+Y.^2) <= r(jj); % The filter is 1 inside radius, 0 outside
%         % imagesc(x,y,filter);
%         cumEnergy(jj,ii)=4*c^3*trapz(trapz(Ed.*filter));
%     end
%     
% %     energyCirc(:,ii) = gradient(cumEnergy(:,ii),r);
%     
%     if stills == 'y'
%         mesh(X*1e9,Y*1e9,Ed)
%         box off
% %         axis equal
% %         colormap parula
%         colorbar
%         caxis([-2 6]*1e4);
% %         xlim([min(x) max(x)]*1e9)
% %         ylim([min(y) max(y)]*1e9)
%         xlabel('x [nm]')
%         ylabel('y [nm]')
%         title('Total energy density (interpolated) [J \cdot m^{-3}]')
%         print([folder 'A_' num2str(ii)],'-r300','-dpng')
%         close(figure)
%     end
end

%%
Edfinal = Edtot/Nfiles;
Amat = Edfinal == 0;
meanEx = sum(Edfinal,1)./(N - sum(Amat,1));
figure
plot(x*1e9,meanEx,'linewidth',1.3)
xlabel('x [nm]')
ylabel('Average E density as a function of x [J \cdot m^{-3}]') 
saveas(gcf, [folder '\Etot_profile_x'], 'fig')

figure
meanEy = sum(Edfinal,2)./(N - sum(Amat,2));
plot(y*1e9,meanEy,'linewidth',1.3)
xlabel('y [nm]')
ylabel('Average E density as a function of y [J \cdot m^{-3}]') 
saveas(gcf, [folder '\Etot_profile_y'], 'fig')

Edfinal(Amat) = NaN;

figure
% Edfinal(Edfinal> 3.5e4) = 0;
imagesc(Edfinal)
colorbar
caxis([min(min(Edfinal)) 3.5e4])
xlabel('x')
ylabel('y')
title('E density [J \cdot m^{-3}]')
saveas(gcf, [folder '\Etot_image'], 'fig')
%%
% 
% figure
% for ii = 1:3:Nfiles
% plot(r,cumEnergy(:,ii),'linewidth',1.2);
% % Plot the cumulative integrated area vs radius
% hold on
% end
% box off
% xlabel('r [nm]')
% ylabel('Cumulative energy [J]')
% hold off
% saveas(gcf, [folder '\Ed_tot_r'], 'fig')
% 
% figure
% for ii = 1:3:Nfiles
% plot(r,energyCirc(:,ii),'linewidth',1.2);
% % Plot the cumulative integrated area vs radius
% hold on
% end
% box off
% xlabel('r [nm]')
% ylabel('Energy density per unit radius [J \cdot m^{-1}]')
% hold off
% saveas(gcf, [folder '\Ed_radius'], 'fig')
% 
% figure
% for ii = 1:3:Nfiles
% plot(r,energyCirc(:,ii)./(2*pi*r'),'linewidth',1.2);
% % Plot the cumulative integrated area vs radius
% hold on
% end
% box off
% xlabel('r [nm]')
% ylabel('E [J \cdot m^{-2}]')
% title('Demagnetizing energy per unit area (averaged around the circumference')
% hold off
% saveas(gcf, [folder '\Ed_area'], 'fig')
% %%
% 
% CC = c*ones(N,1);
% Etot = squeeze(4*c^3*trapz(trapz(EdTensor)));
% 
% figure
% plot(Ku,Etot,'linewidth',1.2)
% box off
% xlabel('K_{u1} [J \cdot m^{-3}]')
% ylabel('Total E_d [J]')
% saveas(gcf, [folder '\Ed_tot'], 'fig')