%% Vortex-antivortex magnetization state peak analyzer
%
%  peakFinder reads from the A_ii.ovf files generated by mumax3 a matrix
%  corresponding to the mz values; performs a five-point 2D Gaussian least
%  squares fit to locate the peak, and plots its position in time.
%
%  To help the program locate a peak when there's "turbulence" in mz, the
%  xSlicel, xSlicer, ySliceu, ySliced parameters can be used to exclude
%  regions containing unwanted peaks.
%
%  For accessory functions, see also: GAUSSIANPEAK RENAMEFILES
%

clear variables
close all

%% Simulation parameters

Nx = 128;
Ny = 128;
c = 2.5e-9;                          % cell size

% N = 201;                           % number of data files
% columns = 1;                       % number of columns of data in the files

xSlicel = 1;                       % data slicing parameters
ySliceu = 1;                       % put l,u = 0 and r,d = 1 for no slicing

xSlicer = 0;
ySliced = 0;

maxVelocity = 550;                  % max velocity of vortex core [m/s]
                                    % use to limit range of vortex search

nFit = 2;                           % number of fitting points (nFit*2 + 1)

% files renaming
rename = true;

% saving of 3D stills
stills = false;
skip = 2;                           % save one still every _skip_ files
quality = 'hq';                     % high quality ('hq') or low quality
                                    %('lq') stills
rf = 3;                             % refinement in hq stills (2 -- 5)

% T simulation yes/no
T = 'yes';

%% Files folder and files rename

dailyFolder = 'D:\Program Files\mumax\Simulazioni\NUOVE\temperature\static\';
simulationFolder = 'temperature_static3\';

folder = [dailyFolder simulationFolder];            % folder containing files
PythonScript = 'batchRenamer.py';                   % Python rename script

% calls the MATLAB wrapper to a pyhton function (requires python 3.5 or
% above)

if rename
    try
        renameFiles(folder,PythonScript);
    catch
        disp('Error: files already renamed. Continuing execution...')
    end
end

%% Check number of header lines

fid = fopen([folder 'A_1.ovf']);
tline = fgets(fid);
header = 0;
while strcmp(tline(1),'#')          % header lines in files have leading #
    tline = fgets(fid);
    header = header + 1;
end
fclose(fid);

%% Extract time from table

fid = fopen([folder 'table.txt']);
fgets(fid);                                     % skip first line
time = cell2mat(textscan(fid, '%f %*[^\n]'));   % read time column, ignore rest
N = length(time);
fclose(fid);

% cut time vector to the number of analyzed points N
if length(time)> N
    %     time(1) = [];
    time = time(1:N);
end

% calculate max interval of vortex search
if maxVelocity ~=0
    dt = mean(gradient(time));
    dMax = ceil(maxVelocity*dt/c);              % max no. of cells moved
end

%%

% preallocation
Mmat = zeros(Nx,Ny);
R = zeros(N,2);
p = zeros(N,1);
rng('shuffle');

% preparation for stills display
if stills
    xP = linspace(-1,1,Nx);
    yP = linspace(-1,1,Ny);
    
    [XI,YI] = meshgrid(linspace(-1,1,rf*Nx),linspace(-1,1,rf*Ny));
    h = waitbar(0,'Stills creation in progress');
end
N = N-4;
% main loop
for ii = 1:N
    % files reading
    fid = fopen([folder 'A_' num2str(ii) '.ovf']);
    
    % skip header lines of file
    for k = 1:header
        fgets(fid);
    end
    
    % read the M columns
    M = cell2mat(textscan(fid,'%f %f %f'));
    fclose(fid);
    
    % select the z coordinate
    Mz = M(:,end);
    
    % put Mz into matrix form
    Mmat = reshape(Mz,[Nx,Ny]);
    Mmat(Mmat == 0) = NaN;
    %%
    Mmat = rot90(Mmat);
    %%
    clear Mz M
    
    % creates stills of 3D visualization of peak
    if stills &&  mod(ii,skip) == 0
        figure('visible','off');
        switch quality
            case 'hq'
                surf(griddata(xP,yP,Mmat,XI,YI,'cubic'),'linestyle', 'none')
            case 'lq'
                mesh(Mmat)
            otherwise
                continue
        end
        zlim([-1 1])
        view(100,40)
        str = [num2str(time(ii),'%10.3e'),' s'];
        dim = [0.69 0.74 0.18 0.1];
        b = annotation('textbox',dim,'String',str,'FitBoxToText','on');
        title('m_{\itz\rm} peak evolution')
        M = getframe(gcf);
        print([folder 'A_' num2str(ii)],'-dpng')
        delete(b)
        close(figure)
        waitbar(ii/N)                           % update the waitbar
    end
    
    % slicing out only "uninteresting" cells
    Mmat([1:xSlicel, end-xSlicer:end],:) = NaN;
    Mmat(:,[1:ySliceu, end-ySliced:end]) = NaN;
    
    % find the location of peak
    if ii == 1
        [maxMz,ind] = max(abs(Mmat(:)));
        [n,m] = ind2sub(size(Mmat),ind);
        nprime = n;
        mprime = m;
    else
        try 
            A = Mmat(n-dMax:n+dMax,m-dMax:m+dMax);
            [maxMz,ind] = max(abs(A(:)));
            nprime = n;
            mprime = m;
            [n,m] = ind2sub(size(A),ind);
            n = n - dMax - 1 + nprime;
            m = m - dMax - 1 + mprime;
        catch
            disp('Warning: peak too close to edge')
            [maxMz,ind] = max(abs(Mmat(:)));
            [n_prime,m_prime] = ind2sub(size(Mmat),ind);
            if (n_prime>1 && n_prime< Nx && m_prime > 2 && m_prime<(Ny-1))
                n = n_prime;
                m = m_prime;
            else
                n = nprime;
                m = mprime;
            end
        end
        clear A
    end
    
    % compute a vortex polarization(+/-1) indicator vector
    p(ii) = Mmat(n,m)./abs(Mmat(n,m));
    
    % perform the Gaussian fit
    if (n + nFit > Nx) || (n- nFit <1) || (m + nFit > Ny) || (m - nFit <1)
        c_x = n;
        c_y = m;
    else
        [c_x,c_y,stdx,stdy] = gaussianPeak(Mmat,m,n,nFit);
    end
    
    %  define initial position as center (0,0)
    if ii == 1
        x0 = c_x;
        y0 = c_y;
    end
    
    x = c_x - x0;
    y = c_y - y0;
    
    % peak position relative to the center
    R(ii,1) = x*c;
    R(ii,2) = y*c;
end


if exist('h','var')
    close(h)
end

% find unphysical peak positions
indices = find(abs([0,0;diff(R)]) > maxVelocity*dt);
offLimitsEvent = 0;

% replace unphysical peak positions with a weighted mean
for jj = 1:length(indices)
    try
    R(indices(jj)) = 1/3 * (0.5*R(indices(jj)-2) + R(indices(jj)-1) + R(indices(jj)+1) + 0.5*R(indices(jj)+2));
    offLimitsEvent = offLimitsEvent + 1;
    catch 
     R(indices(jj)) = (2*R(indices(jj)-1)- R(indices(jj)-2)); 
     disp('Warning: events at the end might be unreliable')
    end
end

if offLimitsEvent >0
    disp('Warning: unphysical peak positions found. Removing...')
end

% velocity of vortex core

Vx = gradient(R(:,1),time);
Vy = gradient(R(:,2),time);

V = sqrt(Vx.^2 + Vy.^2);                        % absolute velocity

% acceleration of vortex core

ax = gradient(Vx,time);
ay = gradient(Vy,time);

results = {R, time, N, V, p, folder};
%%
% save time, positions, velocities
fid = fopen([folder '\saveData.txt'],'wt');
fprintf(fid, 'time [s]\tRx [m]\t\tRy [m]\t\tVx [m/s]\tVy [m/s]\r\n');
fprintf(fid, '%.3e\t%.3e\t%.3e\t%.3e\t%.3e\n', [time,R(:,1),R(:,2),Vx,Vy]');
fclose(fid); %Closes the file

%% Plotting
close all
plotting(results);

%% Fourier fransforms
% FFT of vortex position

[X,~] = fourierTransform(R(:,1),time);
[Y,f] = fourierTransform(R(:,2),time);

string = sprintf('Resonant frequency: %.0f MHz', f(X == max(X)) * 1e-6);
disp(string)

% convert to GHz
F = f*1e-9;

figure
plot(F,X,'linewidth',1.1)
hold on
plot(F,Y,'linewidth',1.1)
xlabel('Frequency [GHz]')
ylabel('Absolute value [arb. units]')
legend('X','Y')
xlim([min(F) max(F)])

title('Normalised Fourier transform of vortex core movement')
saveas(gcf, [folder '\fourier'], 'fig')

fileID = fopen([folder '\resonance.txt'],'w');
fprintf(fileID,string);
fclose(fileID);

% To check if FFT is accurate, find the resonante frequency with another
% method: peak separation
%
% Find peak separation, hardlimited to 1 GHz resonance (> 1 ns)

hardLimit = 1; %GHz

ySignal = R(:,2);
timeStep = mean(diff(time));
meanSignal = mean(ySignal);

% cut the signal at the mean value
ySignal(ySignal< meanSignal) = meanSignal;

% find peaks in the signal, with the hard limit
[~,peaks] = findpeaks(ySignal,'MinPeakDistance', hardLimit*1e-9/timeStep);

% avg distance of peaks gives the period
freqAlt = 1/mean(diff(time(peaks)));

fprintf('Alternate resonant frequency: %.0f MHz\n', freqAlt*1e-6);

%% Denoising and compare (for T simulation)
%
% Filter positions with a Savitzsky-Golay filter, plot them against time
%

if strcmp(T,'yes')
    Xs = SFilt(R(:,1),time);
    Ys = SFilt(R(:,2),time);
    
    auxstr = sprintf('Y %.2f nm', Ys.amplitudeRMS * 1e9);
    string2 = sprintf('RMS VC movement: X %.2f nm\r\n %25s' , Xs.amplitudeRMS * 1e9, auxstr);
    disp(string2)
    
    xC = mean(Xs.signal);
    yC = mean(Ys.signal);
    
    figure
    plot3(time,Xs.signal,Ys.signal,'linewidth',2)
    hold on
    plot3(time,ones(length(time))*xC, ones(length(time))*yC,'k--','linewidth',3)
    view([17.3, 33.2])
    grid on
    xlabel('Time [s]')
    ylabel('X [nm]')
    zlabel('Y [nm]')
    title('Vortex core movement (smoothed)')
    
    fileID = fopen([folder '\VC_RMS.txt'],'w');
    fprintf(fileID,string2);
    fclose(fileID);
    
    saveas(gcf, [folder '\VCD'], 'fig') 
end

%% R RMS
%
% RMS and average distance of VC from the centre (for static T simulations)
%

tCO = 1e-8;        % Cutoff time

if max(time) > tCO
    
    AA = time >= tCO;
    bb = find(AA);
    
    VRMS = sqrt(1/(time(end) - time(bb(1))) * trapz(time(AA), V(AA).^2));
    
    R_RMS = VRMS/(2*pi*f(X == max(X)));
    fprintf('RMS distance from centre: %.2f nm\n', R_RMS*1e9)
    
    V_avg = mean(V(AA));
    stringV = sprintf('Mean velocity: %.1f m/s\n',V_avg);
    disp(stringV)
    
    R_avg = mean(sqrt(R(AA,1).^2 + R(AA,2).^2));
    stringR = sprintf('Average distance from centre: %.2f nm\n', R_avg*1e9);
    disp(stringR)
    fileID = fopen([folder '\VC_Vmean.txt'],'w');
    fprintf(fileID,stringV);
    fprintf(fileID,stringR);
    fclose(fileID);
    
    % data binning
    nbins = 40;
    Rad = sqrt(R(AA,1).^2 + R(AA,2).^2);
    %cut data beyond threshold
    thresholdCutoff = 8e-9;
    edges = linspace(0,thresholdCutoff,nbins+1);
    [N,edges] = histcounts(Rad,edges);
    edges(1) = [];
    edges = edges - (edges(2) - edges(1))/2;
    
    figure
    
    scatter(edges*1e9,N,'filled')
    xlabel('R [nm]')
    ylabel('{\it f(R)\cdotdR} [arb. units]')
    title('Sampling of the thermal distribution of the vortex core around the centre')
    saveas(gcf, [folder '\distr'], 'fig')
end

%% Energy
%
% In T simulations, read the energy and plot it against time
%

if strcmp(T,'yes')
    
    fid = fopen([folder 'table.txt']);
    fgets(fid);                                     % skip first line
    data = cell2mat(textscan(fid, '%f %f %f %f %f %f %f %f %f %f %f %f %*[^\n]'));
    Etot = data(:,6);
    Etherm = data(:,12);
    clear data
    fclose(fid);
    
    inversionPoint = find(p < 0, 1) - 1;
    
    figure
    a = plot(time*1e9,Etot,'linewidth',1.2);
    hold on
    b = plot(time*1e9,Etot - Etherm,'linewidth',1.2);
    c = plot(time*1e9,abs(Etherm),'k','linewidth',0.8);
    d = scatter(time(inversionPoint)*1e9,Etot(inversionPoint),'r','filled');
    xlabel('time [ns]')
    ylabel('Energy [J]')
    legend([a,c,b,d],'Total energy','Thermal energy','Non-thermal energy','Reversal point')
    legend('boxoff')
    title('Energy of the system during reversal')
    saveas(gcf, [folder '\energy'], 'fig')
    hold off
    
end