%% Vortex-antivortex magnetization state peak analyzer
%
%  peakFinder reads from the A_ii.ovf files generated by mumax3 a matrix
%  corresponding to the mz values; performs a five-point 2D Gaussian least
%  squares fit to locate the peak, and plots its position in time.
%
%  To help the program locate a peak when there's "turbulence" in mz, the
%  xSlicel, xSlicer, ySliceu, ySliced parameters can be used to exclude
%  regions containing unwanted peaks.
%
%  For accessory functions, see also: GAUSSIANPEAK RENAMEFILES
%

clear variables
close all

%% Simulation parameters

Nx = 200;
Ny = 120;
c = 5e-9;                          % cell size

N = 619;                           % number of data files
% columns = 1;                     % number of columns of data in the files

xSlicel = 1;                       % data slicing parameters
ySliceu = 1;                       % put l,u = 0 and r,d = 1 for no slicing

xSlicer = 0;
ySliced = 0;

maxVelocity = 550;                  % max velocity of vortex core [m/s] 
                                    % use to limit range of vortex search
                                    % if == 0 the range is not limited

nFit = 2;                           % fitting points parameter

% files renaming
rename = false;

% saving of 3D stills
stills = false;
skip = 3;                           % save one still every _skip_ files

%% Files folder and files rename

dailyFolder = 'D:\Program Files\mumax\Simulazioni\SIMULAZIONI 16-5\';
simulationFolder = 'elliptical_dot_current_1\';

folder = [dailyFolder simulationFolder];            % folder containing files
PythonScript = 'batchRenamer.py';                   % Python rename script

% calls the MATLAB wrapper to a pyhton function (requires python 3.5 or
% above)

if rename
    renameFiles(folder,PythonScript);
end

%% Check number of header lines

fid = fopen([folder 'A_1.ovf']);
tline = fgets(fid);
header = 0;
while strcmp(tline(1),'#')                      % header lines have leading #
    tline = fgets(fid);
    header = header+1;
end
fclose(fid);

%% Extract time from table

fid = fopen([folder 'table.txt']);
fgets(fid);                                     % skip first line
time = cell2mat(textscan(fid, '%f %*[^\n]'));   % read time column, ignore rest
fclose(fid);

% cut time vector to the number of analyzed points N
if length(time)> N
    time(1) = [];
    time = time(1:N);
end

% calculate max interval of vortex search
if maxVelocity ~=0
    dt = time(2) - time(1);
    dMax = ceil(maxVelocity*dt/c);              % max no. of cells moved
end

%%

% preallocation
Mmat = zeros(Nx,Ny);
R = zeros(N,2);
p = zeros(N,1);

if stills
    h = waitbar(0,'Stills creation in progress');
end



for ii = 1:N
    fid = fopen([folder 'A_' num2str(ii) '.ovf']);
    
    % skip header lines of file
    for k = 1:header
        fgets(fid);
    end
    
    % read the Mz column
    Mz = cell2mat(textscan(fid,'%f'));
    fclose(fid);
    
    % put Mz into matrix form
    Mmat = reshape(Mz,[Nx,Ny]);
    Mmat(Mmat == 0) = NaN;
    
    clear Mz
    
    % creates stills of 3D visualization of peak
    if stills &&  mod(ii,skip) == 0
        figure('visible','off');
        mesh(Mmat)
        zlim([-1 1])
        view(100,40)
        str = [num2str(time(ii),'%10.3e'),' s'];
        dim = [0.69 0.74 0.18 0.1];
        b = annotation('textbox',dim,'String',str,'FitBoxToText','on');
        title('m_{\itz\rm} peak evolution')
        M = getframe(gcf);
        print([folder 'A_' num2str(ii)],'-dpng')
        close(figure)
        delete(b)
        waitbar(ii/N)                           % update the waitbar
    end
    
%     K(:,:,ii) = Mmat(:,:);
    
    % slicing out only "uninteresting" cells
    Mmat([1:xSlicel, end-xSlicer:end],:) = NaN;
    Mmat(:,[1:ySliceu, end-ySliced:end]) = NaN;
    
    % find the location of peak
    if ii == 1
        [maxMz,ind] = max(abs(Mmat(:)));
        [n,m] = ind2sub(size(Mmat),ind);
    else
        A = Mmat(n-dMax:n+dMax,m-dMax:m+dMax);
        [maxMz,ind] = max(abs(A(:)));
        nprime = n;
        mprime = m;
        [n,m] = ind2sub(size(A),ind);
        n = n - dMax - 1 + nprime;
        m = m - dMax - 1 + mprime;
        clear A
    end
    
    
    % compute a vortex polarization(+/-1) indicator vector
    p(ii) = Mmat(n,m)./abs(Mmat(n,m));
    
    % perform the Gaussian fit
    if (n + nFit > Nx) || (n- nFit <1) || (m + nFit > Ny) || (m - nFit <1)
        c_x = n;
        c_y = m;
    else
    [c_x,c_y,stdx,stdy] = gaussianPeak(Mmat,m,n,nFit);
    end
    
    %  define initial position as center (0,0)    
    if ii == 1
        x0 = c_x;
        y0 = c_y;
    end
    
    x = c_x - x0;
    y = c_y - y0;
    
    % peak position relative to the center
    R(ii,1) = x*c;
    R(ii,2) = y*c;
end

if exist('h','var')
      close(h)
end

% velocity of vortex core

Vx = gradient(R(:,1),time);
Vy = gradient(R(:,2),time);

V = sqrt(Vx.^2 + Vy.^2);                        % absolute velocity

% acceleration of vortex core

ax = gradient(Vx,time);
ay = gradient(Vy,time);

results = {R, time, N, V, p, folder};

%% Plotting

plotting(results);